// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBSetup.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20241231230836_FD_GROUP")]
    partial class FD_GROUP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodGroup", b =>
                {
                    b.Property<string>("FdGrp_Cd")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("FdGrp_Cd")
                        .HasComment("4-digit code identifying a food group. Only the first 2 ndigits are currently assigned. In the future, the last 2 digits may be used. Codes may not be consecutive.");

                    b.Property<string>("FdGrp_Desc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("FdGrp_Desc")
                        .HasComment("Name of food group.");

                    b.HasKey("FdGrp_Cd");

                    b.ToTable("FD_GROUP", t =>
                        {
                            t.HasComment("Contains a list of food groups used in SR28 and their descriptions.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
