// <auto-generated />
using DBSetup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBSetup.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20250103054738_NutData4")]
    partial class NutData4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBSetup.DataSource", b =>
                {
                    b.Property<string>("DataSourceId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("DataSrc_ID")
                        .HasComment("Unique ID identifying the reference/source.");

                    b.Property<string>("Authors")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Authors")
                        .HasComment("List of authors for a journal article or name of sponsoring organization for other documents.");

                    b.Property<string>("End_Page")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("End_Page")
                        .HasComment("Ending page number of article/document.");

                    b.Property<string>("Issue_State")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Issue_State")
                        .HasComment("Issue number for journal article; State where the sponsoring organization is located.");

                    b.Property<string>("Journal")
                        .HasMaxLength(135)
                        .HasColumnType("nvarchar(135)")
                        .HasColumnName("Journal")
                        .HasComment("Name of the journal in which the article was published.");

                    b.Property<string>("NutrientDataFoodDescriptionId")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NutrientDataNutrientDefinitionId")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Start_Page")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Start_Page")
                        .HasComment("Starting page number of article/document.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title")
                        .HasComment("Title of article or name of document, such as a report from a company or trade association.");

                    b.Property<string>("Vol_City")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Vol_City")
                        .HasComment("Volume number for journal articles, books, or reports; city where sponsoring organization is located.");

                    b.Property<string>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Year")
                        .HasComment("Year article or document was published.");

                    b.HasKey("DataSourceId");

                    b.HasIndex("NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId");

                    b.ToTable("DATA_SRC", t =>
                        {
                            t.HasComment("This file provides a citation to the DataSrc_ID in the Sources of Data Link file.");
                        });
                });

            modelBuilder.Entity("DBSetup.DataSourceLink", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<string>("NutrientDefinitionId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Nutr_No")
                        .HasComment("Unique 3-digit identifier code for a nutrient.");

                    b.Property<string>("DataSourceId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("DataSrc_ID")
                        .HasComment("Unique ID identifying the reference/source.");

                    b.HasKey("FoodDescriptionId", "NutrientDefinitionId", "DataSourceId");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("NutrientDefinitionId");

                    b.ToTable("DATSRCLN", t =>
                        {
                            t.HasComment("This file is used to link the Nutrient Data file with the Sources of Data table. It is needed to resolve the many-to-many relationship between the two tables.");
                        });
                });

            modelBuilder.Entity("DBSetup.DerivationCode", b =>
                {
                    b.Property<string>("DerivationCodeId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Deriv_Cd")
                        .HasComment("Derivation Code.");

                    b.Property<string>("DerivationCodeDescription")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Deriv_Desc")
                        .HasComment("Description of derivation code giving specific information on how the value was determined.");

                    b.HasKey("DerivationCodeId");

                    b.ToTable("DERIVCD", t =>
                        {
                            t.HasComment("This file provides information on how the nutrient values were determined. The file contains the derivation codes and their descriptions.");
                        });
                });

            modelBuilder.Entity("DBSetup.FoodDescription", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<decimal?>("CHO_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for calculating calories from carbohydrate.");

                    b.Property<string>("ComName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Other names commonly used to describe a food, including local or regional names for various foods, for example, 'soda' or 'pop' for 'carbonated beverages.'");

                    b.Property<decimal?>("Fat_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for calculating calories from fat.");

                    b.Property<string>("FoodGroupId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("FdGrp_Cd")
                        .HasComment("4-digit code indicating food group to which a food item belongs.");

                    b.Property<string>("Long_Desc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Long_Desc")
                        .HasComment("200-character description of food item.");

                    b.Property<string>("ManufacName")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasComment("Indicates the company that manufactured the product, when appropriate.");

                    b.Property<decimal?>("N_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for converting nitrogen to protein.");

                    b.Property<decimal?>("Pro_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for calculating calories from protein.");

                    b.Property<string>("Ref_desc")
                        .HasMaxLength(135)
                        .HasColumnType("nvarchar(135)")
                        .HasComment("Description of inedible parts of a food item (refuse), such as seeds or bone.");

                    b.Property<decimal?>("Refuse")
                        .HasPrecision(2)
                        .HasColumnType("decimal(2,0)")
                        .HasComment("Percentage of refuse.");

                    b.Property<string>("SciName")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasComment("Scientific name of the food item. Given for the least processed form of the food (usually raw), if applicable.");

                    b.Property<string>("Shrt_Desc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Shrt_Desc")
                        .HasComment("60-character abbreviated description of food item. Generated from the 200-character description using abbreviations in Appendix A. If short description is longer than 60 characters, additional abbreviations are made. ");

                    b.Property<string>("Survey")
                        .HasColumnType("nvarchar(1)")
                        .HasComment("Indicates if the food item is used in the USDA Food and Nutrient Database for Dietary Studies (FNDDS) and thus has a complete nutrient profile for the 65 FNDDS nutrients.");

                    b.HasKey("FoodDescriptionId");

                    b.HasIndex("FoodGroupId");

                    b.ToTable("FOOD_DES", t =>
                        {
                            t.HasComment("This file contains long and short descriptions and food group designators for all food items, along with common names, manufacturer name, scientific name, percentage and description of refuse, and factors used for calculating protein and kilocalories, if applicable. Items used in the FNDDS are also identified by value of 'Y' in the Survey field. ");
                        });
                });

            modelBuilder.Entity("DBSetup.FoodGroup", b =>
                {
                    b.Property<string>("FoodGroupId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("FdGrp_Cd")
                        .HasComment("4-digit code identifying a food group. Only the first 2 ndigits are currently assigned. In the future, the last 2 digits may be used. Codes may not be consecutive.");

                    b.Property<string>("FoodGroupName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("FdGrp_Desc")
                        .HasComment("Name of food group.");

                    b.HasKey("FoodGroupId");

                    b.ToTable("FD_GROUP", t =>
                        {
                            t.HasComment("Contains a list of food groups used in SR28 and their descriptions.");
                        });
                });

            modelBuilder.Entity("DBSetup.Footnote", b =>
                {
                    b.Property<int>("FootnoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FootnoteId"));

                    b.Property<string>("FoodDescriptionId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<string>("Footnt_No")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Footnt_No")
                        .HasComment("Sequence number. If a given footnote applies to more than one nutrient number, the same footnote number is used. As a result, this file cannot be indexed and there is no primary key. ");

                    b.Property<string>("Footnt_Txt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Footnt_Txt")
                        .HasComment("Footnote text.");

                    b.Property<string>("Footnt_Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Footnt_Typ")
                        .HasComment("Type of footnote: D = footnote adding information to the food description;  M = footnote adding information to measure description;  N = footnote providing additional information on a nutrient value. If the Footnt_typ = N, the Nutr_No will also be filled in.");

                    b.Property<string>("NutrientDefinitionId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Nutr_No")
                        .HasComment("Unique 3-digit identifier code for a nutrient to which footnote applies.");

                    b.HasKey("FootnoteId");

                    b.HasIndex("FoodDescriptionId");

                    b.HasIndex("NutrientDefinitionId");

                    b.ToTable("FOOTNOTE", t =>
                        {
                            t.HasComment("This file contains additional information about the food item, household weight, and nutrient value.");
                        });
                });

            modelBuilder.Entity("DBSetup.LanguaLDescription", b =>
                {
                    b.Property<string>("LangualDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Factor_Code")
                        .HasComment("The LanguaL factor from the Thesaurus. Only those codes used to factor the foods contained in the LanguaL Factor file are included in this file. ");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)")
                        .HasColumnName("Description")
                        .HasComment("The description of the LanguaL Factor Code from the thesaurus. ");

                    b.HasKey("LangualDescriptionId");

                    b.ToTable("LANGDESC", t =>
                        {
                            t.HasComment("This file is a support file to the LanguaL Factor file and contains the descriptions for only those factors used in coding the selected food items codes in this release of SR.");
                        });
                });

            modelBuilder.Entity("DBSetup.LanguaLFactor", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<string>("LangualDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Factor_Code")
                        .HasComment("The LanguaL factor from the Thesaurus.");

                    b.HasKey("FoodDescriptionId", "LangualDescriptionId");

                    b.HasIndex("LangualDescriptionId");

                    b.ToTable("LANGUAL", t =>
                        {
                            t.HasComment("This file is a support file to the Food Description file and contains the factors from the LanguaL Thesaurus used to code a particular food.");
                        });
                });

            modelBuilder.Entity("DBSetup.NutrientData", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item.  If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<string>("NutrientDefinitionId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Nutr_No")
                        .HasComment("Unique 3-digit identifier code for a nutrient.");

                    b.Property<string>("AddMod_Date")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AddMod_Date")
                        .HasComment("Indicates when a value was either added to the database or last modified.");

                    b.Property<string>("Add_Nutr_Mark")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Add_Nutr_Mark")
                        .HasComment("Indicates a vitamin or mineral added for fortification or enrichment. This field is populated for ready-to eat breakfast cereals and many brand-name hot cereals in food group 08.");

                    b.Property<string>("CC")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CC")
                        .HasComment("Confidence Code indicating data quality, based on evaluation of sample plan, sample handling, analytical method, analytical quality control, and number of samples analysed. Not included in this release, but is planned for future releases.");

                    b.Property<decimal?>("DF")
                        .HasPrecision(4)
                        .HasColumnType("decimal(4,0)")
                        .HasColumnName("DF")
                        .HasComment("Degrees of freedom.");

                    b.Property<string>("DerivationCodeId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Deriv_Cd")
                        .HasComment("Data Derivation Code giving specific information on how the value is determined. This field is populated only for items added or updated starting with SR14. This field may not be populated if older records were used in the calculation of the mean value.");

                    b.Property<string>("FoodDescriptionId1")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FoodDescriptionRefId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Ref_NDB_No")
                        .HasComment("NDB number of the item used to calculate a missing value. Populated only for items added or updated starting with SR14.");

                    b.Property<decimal?>("Low_EB")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("Low_EB")
                        .HasComment("Lower 95% error bound.");

                    b.Property<decimal?>("Max")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("Max")
                        .HasComment("Maximum value.");

                    b.Property<decimal?>("Min")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("Min")
                        .HasComment("Minimum value.");

                    b.Property<decimal>("Num_Data_Pts")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)")
                        .HasColumnName("Num_Data_Pts")
                        .HasComment("Number of data points is the number of analyses used to calculate the nutrient value. If the number of data points is 0, the value was calculated or imputed.");

                    b.Property<decimal?>("Num_Studies")
                        .HasPrecision(2)
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("Num_Studies")
                        .HasComment("Number of studies.");

                    b.Property<decimal>("Nutr_Val")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("Nutr_Val")
                        .HasComment("Amount in 100 grams, edible portion.");

                    b.Property<string>("SourceCodeId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Src_Cd")
                        .HasComment("Code indicating type of data.");

                    b.Property<string>("Stat_cmt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Stat_cmt")
                        .HasComment("Statistical comments.");

                    b.Property<decimal?>("Std_Error")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("Std_Error")
                        .HasComment("Standard error of the mean. Null if cannot be calculated. The standard error is also not given if the number of data points is less than three.");

                    b.Property<decimal?>("Up_EB")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("Up_EB")
                        .HasComment("Upper 95% error bound.");

                    b.HasKey("FoodDescriptionId", "NutrientDefinitionId");

                    b.HasIndex("DerivationCodeId");

                    b.HasIndex("FoodDescriptionId1");

                    b.HasIndex("FoodDescriptionRefId");

                    b.HasIndex("NutrientDefinitionId");

                    b.HasIndex("SourceCodeId");

                    b.ToTable("NUT_DATA", t =>
                        {
                            t.HasComment("This file contains the nutrient values and information about the values, including expanded statistical information.");
                        });
                });

            modelBuilder.Entity("DBSetup.NutrientDefinition", b =>
                {
                    b.Property<string>("NutrientDefinitionId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Nutr_No")
                        .HasComment("Unique 3-digit identifier code for a nutrient.");

                    b.Property<string>("Num_Dec")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Num_Dec")
                        .HasComment("Number of decimal places to which a nutrient value is rounded.");

                    b.Property<string>("NutrDesc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("NutrDesc")
                        .HasComment("Name of nutrient/food component.");

                    b.Property<string>("SR_Order")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("SR_Order")
                        .HasComment("Used to sort nutrient records in the same order as \r\nvarious reports produced from SR.");

                    b.Property<string>("TagName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tagname")
                        .HasComment("International Network of Food Data Systems (INFOODS) Tagnames. A unique abbreviation for a nutrient/food component developed by INFOODS to aid in the interchange of data.");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("Units")
                        .HasComment("Units of measure (mg, g, μg, and so on).");

                    b.HasKey("NutrientDefinitionId");

                    b.ToTable("NUTR_DEF", t =>
                        {
                            t.HasComment("This file is a support file to the Nutrient Data file. It provides the 3-digit nutrient code, unit of measure, INFOODS tagname, and description.");
                        });
                });

            modelBuilder.Entity("DBSetup.SourceCode", b =>
                {
                    b.Property<string>("SourceCodeId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Src_Cd")
                        .HasComment("A 2-digit code indicating type of data.");

                    b.Property<string>("SourceCodeDescription")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("SrcCd_Desc")
                        .HasComment("Description of source code that identifies the type of nutrient data.");

                    b.HasKey("SourceCodeId");

                    b.ToTable("SRC", t =>
                        {
                            t.HasComment("This file contains codes indicating the type of data (analytical, calculated, assumed zero, and so on) in the Nutrient Data file. To improve the usability of the database and to provide values for the FNDDS, NDL staff imputed nutrient values for a number of proximate components, total dietary fiber, total sugar, and vitamin and mineral values.");
                        });
                });

            modelBuilder.Entity("DBSetup.Weight", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item.  If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<string>("Seq")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Seq")
                        .HasComment("Sequence number.");

                    b.Property<decimal>("Amount")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("Amount")
                        .HasComment("Unit modifier (for example, 1 in '1 cup').");

                    b.Property<decimal>("Gm_Wgt")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)")
                        .HasColumnName("Gm_Wgt")
                        .HasComment("Gram weight.");

                    b.Property<string>("Msre_Desc")
                        .IsRequired()
                        .HasMaxLength(84)
                        .HasColumnType("nvarchar(84)")
                        .HasColumnName("Msre_Desc")
                        .HasComment("Description (for example, cup, diced, and 1-inch pieces)");

                    b.Property<decimal?>("Num_Data_Pts")
                        .HasPrecision(4)
                        .HasColumnType("decimal(4,0)")
                        .HasColumnName("Num_Data_Pts")
                        .HasComment("Number of data points.");

                    b.Property<string>("NutrientDataFoodDescriptionId")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NutrientDataNutrientDefinitionId")
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Std_Dev")
                        .HasPrecision(7, 3)
                        .HasColumnType("decimal(7,3)")
                        .HasColumnName("Std_Dev")
                        .HasComment("Standard deviation.");

                    b.HasKey("FoodDescriptionId", "Seq");

                    b.HasIndex("NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId");

                    b.ToTable("WEIGHT", t =>
                        {
                            t.HasComment("This file contains codes indicating the type of data (analytical, calculated, assumed zero, and so on) in the Nutrient Data file. To improve the usability of the database and to provide values for the FNDDS, NDL staff imputed nutrient values for a number of proximate components, total dietary fiber, total sugar, and vitamin and mineral values.");
                        });
                });

            modelBuilder.Entity("FootnoteNutrientData", b =>
                {
                    b.Property<int>("FootnotesFootnoteId")
                        .HasColumnType("int");

                    b.Property<string>("NutrientDataFoodDescriptionId")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NutrientDataNutrientDefinitionId")
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("FootnotesFootnoteId", "NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId");

                    b.HasIndex("NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId");

                    b.ToTable("FootnoteNutrientData");
                });

            modelBuilder.Entity("DBSetup.DataSource", b =>
                {
                    b.HasOne("DBSetup.NutrientData", null)
                        .WithMany("DataSources")
                        .HasForeignKey("NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId");
                });

            modelBuilder.Entity("DBSetup.DataSourceLink", b =>
                {
                    b.HasOne("DBSetup.DataSource", "DataSource")
                        .WithMany("DataSourceLinks")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.FoodDescription", "FoodDescription")
                        .WithMany()
                        .HasForeignKey("FoodDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.NutrientDefinition", "NutrientDefinition")
                        .WithMany("DataSourceLinks")
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("FoodDescription");

                    b.Navigation("NutrientDefinition");
                });

            modelBuilder.Entity("DBSetup.FoodDescription", b =>
                {
                    b.HasOne("DBSetup.FoodGroup", "FoodGroup")
                        .WithMany("FoodDescriptions")
                        .HasForeignKey("FoodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodGroup");
                });

            modelBuilder.Entity("DBSetup.Footnote", b =>
                {
                    b.HasOne("DBSetup.FoodDescription", "FoodDescription")
                        .WithMany("Footnotes")
                        .HasForeignKey("FoodDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.NutrientDefinition", "NutrientDefinition")
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId");

                    b.Navigation("FoodDescription");

                    b.Navigation("NutrientDefinition");
                });

            modelBuilder.Entity("DBSetup.LanguaLFactor", b =>
                {
                    b.HasOne("DBSetup.FoodDescription", "FoodDescription")
                        .WithMany("LanguaLFactors")
                        .HasForeignKey("FoodDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.LanguaLDescription", "LanguaLDescription")
                        .WithMany("LanguaLFactors")
                        .HasForeignKey("LangualDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodDescription");

                    b.Navigation("LanguaLDescription");
                });

            modelBuilder.Entity("DBSetup.NutrientData", b =>
                {
                    b.HasOne("DBSetup.DerivationCode", "DerivationCode")
                        .WithMany("NutrientData")
                        .HasForeignKey("DerivationCodeId");

                    b.HasOne("DBSetup.FoodDescription", "FoodDescription")
                        .WithMany()
                        .HasForeignKey("FoodDescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBSetup.FoodDescription", null)
                        .WithMany("NutrientData")
                        .HasForeignKey("FoodDescriptionId1");

                    b.HasOne("DBSetup.FoodDescription", "FoodDescriptionRef")
                        .WithMany()
                        .HasForeignKey("FoodDescriptionRefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DBSetup.NutrientDefinition", "NutrientDefinition")
                        .WithMany("NutrientData")
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.SourceCode", "SourceCode")
                        .WithMany("NutrientData")
                        .HasForeignKey("SourceCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerivationCode");

                    b.Navigation("FoodDescription");

                    b.Navigation("FoodDescriptionRef");

                    b.Navigation("NutrientDefinition");

                    b.Navigation("SourceCode");
                });

            modelBuilder.Entity("DBSetup.Weight", b =>
                {
                    b.HasOne("DBSetup.FoodDescription", "FoodDescription")
                        .WithMany("Weights")
                        .HasForeignKey("FoodDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.NutrientData", "NutrientData")
                        .WithMany("Weights")
                        .HasForeignKey("NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId");

                    b.Navigation("FoodDescription");

                    b.Navigation("NutrientData");
                });

            modelBuilder.Entity("FootnoteNutrientData", b =>
                {
                    b.HasOne("DBSetup.Footnote", null)
                        .WithMany()
                        .HasForeignKey("FootnotesFootnoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.NutrientData", null)
                        .WithMany()
                        .HasForeignKey("NutrientDataFoodDescriptionId", "NutrientDataNutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBSetup.DataSource", b =>
                {
                    b.Navigation("DataSourceLinks");
                });

            modelBuilder.Entity("DBSetup.DerivationCode", b =>
                {
                    b.Navigation("NutrientData");
                });

            modelBuilder.Entity("DBSetup.FoodDescription", b =>
                {
                    b.Navigation("Footnotes");

                    b.Navigation("LanguaLFactors");

                    b.Navigation("NutrientData");

                    b.Navigation("Weights");
                });

            modelBuilder.Entity("DBSetup.FoodGroup", b =>
                {
                    b.Navigation("FoodDescriptions");
                });

            modelBuilder.Entity("DBSetup.LanguaLDescription", b =>
                {
                    b.Navigation("LanguaLFactors");
                });

            modelBuilder.Entity("DBSetup.NutrientData", b =>
                {
                    b.Navigation("DataSources");

                    b.Navigation("Weights");
                });

            modelBuilder.Entity("DBSetup.NutrientDefinition", b =>
                {
                    b.Navigation("DataSourceLinks");

                    b.Navigation("NutrientData");
                });

            modelBuilder.Entity("DBSetup.SourceCode", b =>
                {
                    b.Navigation("NutrientData");
                });
#pragma warning restore 612, 618
        }
    }
}
