// <auto-generated />
using DBSetup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBSetup.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20250101235722_SqlServer")]
    partial class SqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBSetup.FoodDescription", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item.  If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<decimal?>("CHO_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for calculating calories from carbohydrate.");

                    b.Property<string>("ComName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Other names commonly used to describe a food, including local or regional names for various foods, for example, 'soda' or 'pop' for 'carbonated beverages.'");

                    b.Property<decimal?>("Fat_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for calculating calories from fat.");

                    b.Property<string>("FoodGroupId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("FdGrp_Cd")
                        .HasComment("4-digit code indicating food group to which a food item belongs.");

                    b.Property<string>("Long_Desc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Long_Desc")
                        .HasComment("200-character description of food item.");

                    b.Property<string>("ManufacName")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasComment("Indicates the company that manufactured the product, when appropriate.");

                    b.Property<decimal?>("N_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for converting nitrogen to protein.");

                    b.Property<decimal?>("Pro_Factor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Factor for calculating calories from protein.");

                    b.Property<string>("Ref_desc")
                        .HasMaxLength(135)
                        .HasColumnType("nvarchar(135)")
                        .HasComment("Description of inedible parts of a food item (refuse), such as seeds or bone.");

                    b.Property<decimal?>("Refuse")
                        .HasPrecision(2)
                        .HasColumnType("decimal(2,0)")
                        .HasComment("Percentage of refuse.");

                    b.Property<string>("SciName")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasComment("Scientific name of the food item. Given for the least processed form of the food (usually raw), if applicable.");

                    b.Property<string>("Shrt_Desc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Shrt_Desc")
                        .HasComment("60-character abbreviated description of food item. Generated from the 200-character description using abbreviations in Appendix A. If short description is longer than 60 characters, additional abbreviations are made. ");

                    b.Property<string>("Survey")
                        .HasColumnType("nvarchar(1)")
                        .HasComment("Indicates if the food item is used in the USDA Food and Nutrient Database for Dietary Studies (FNDDS) and thus has a complete nutrient profile for the 65 FNDDS nutrients.");

                    b.HasKey("FoodDescriptionId");

                    b.HasIndex("FoodGroupId");

                    b.ToTable("FOOD_DES", t =>
                        {
                            t.HasComment("This file contains long and short descriptions and food group designators for all food items, along with common names, manufacturer name, scientific name, percentage and description of refuse, and factors used for calculating protein and kilocalories, if applicable. Items used in the FNDDS are also identified by value of 'Y' in the Survey field. ");
                        });
                });

            modelBuilder.Entity("DBSetup.FoodGroup", b =>
                {
                    b.Property<string>("FoodGroupId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("FdGrp_Cd")
                        .HasComment("4-digit code identifying a food group. Only the first 2 ndigits are currently assigned. In the future, the last 2 digits may be used. Codes may not be consecutive.");

                    b.Property<string>("FoodGroupName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("FdGrp_Desc")
                        .HasComment("Name of food group.");

                    b.HasKey("FoodGroupId");

                    b.ToTable("FD_GROUP", t =>
                        {
                            t.HasComment("Contains a list of food groups used in SR28 and their descriptions.");
                        });
                });

            modelBuilder.Entity("DBSetup.LangualDescription", b =>
                {
                    b.Property<string>("LangualDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Factor_Code")
                        .HasComment("The LanguaL factor from the Thesaurus. Only those codes used to factor the foods contained in the LanguaL Factor file are included in this file. ");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)")
                        .HasColumnName("Description")
                        .HasComment("The description of the LanguaL Factor Code from the thesaurus. ");

                    b.HasKey("LangualDescriptionId");

                    b.ToTable("LANGDESC", t =>
                        {
                            t.HasComment("This file is a support file to the LanguaL Factor file and contains the descriptions for only those factors used in coding the selected food items codes in this release of SR.");
                        });
                });

            modelBuilder.Entity("DBSetup.LangualFactor", b =>
                {
                    b.Property<string>("FoodDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NDB_No")
                        .HasComment("5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.");

                    b.Property<string>("LangualDescriptionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Factor_Code")
                        .HasComment("The LanguaL factor from the Thesaurus.");

                    b.HasKey("FoodDescriptionId", "LangualDescriptionId");

                    b.HasIndex("LangualDescriptionId");

                    b.ToTable("LANGUAL", t =>
                        {
                            t.HasComment("This file is a support file to the Food Description file and contains the factors from the LanguaL Thesaurus used to code a particular food.");
                        });
                });

            modelBuilder.Entity("DBSetup.FoodDescription", b =>
                {
                    b.HasOne("DBSetup.FoodGroup", "FoodGroup")
                        .WithMany("FoodDescriptions")
                        .HasForeignKey("FoodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodGroup");
                });

            modelBuilder.Entity("DBSetup.LangualFactor", b =>
                {
                    b.HasOne("DBSetup.FoodDescription", "FoodDescription")
                        .WithMany("LangualFactors")
                        .HasForeignKey("FoodDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSetup.LangualDescription", "LangualDescription")
                        .WithMany("LangualFactors")
                        .HasForeignKey("LangualDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodDescription");

                    b.Navigation("LangualDescription");
                });

            modelBuilder.Entity("DBSetup.FoodDescription", b =>
                {
                    b.Navigation("LangualFactors");
                });

            modelBuilder.Entity("DBSetup.FoodGroup", b =>
                {
                    b.Navigation("FoodDescriptions");
                });

            modelBuilder.Entity("DBSetup.LangualDescription", b =>
                {
                    b.Navigation("LangualFactors");
                });
#pragma warning restore 612, 618
        }
    }
}
